# This Makefile is invoked by COPR to build SRPM.
# https://docs.pagure.org/copr.copr/user_documentation.html#make-srpm
#
# The Makefile's target is invoked like this:
# make -f .copr/Makefile srpm outdir="<outdir>" spec="<spec_path>"

srpm:
	.copr/build-srpm "$(outdir)"
